# Generated by Django 5.2.7 on 2025-10-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_1',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='image_2',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='image_3',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='image_4',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
