# Generated by Django 5.2.7 on 2025-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_image_1_room_image_2_room_image_3_room_image_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_1',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_2',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_3',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_4',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
    ]
