# Generated by Django 5.2.7 on 2025-11-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=150)),
                ('body', models.TextField()),
            ],
        ),
    ]
