# Generated by Django 5.2.7 on 2025-11-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_weblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='blog_image',
            field=models.ImageField(default='fallback.png', upload_to=''),
        ),
    ]
