# Generated by Django 5.2.7 on 2025-11-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_weblog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
